buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.3.1'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://www.jitpack.io' }
        maven { url "https://artifactory.appodeal.com/appodeal-public" }
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
    project.evaluationDependsOn(':app')
    configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.arthenica' && details.requested.name == 'ffmpeg-kit-https') {
                details.useTarget group: 'com.arthenica', name: 'ffmpeg-kit-full-gpl', version: '6.0.LTS'
            }
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
